import { addDoc, collection, doc, getDoc, getDocs, query, serverTimestamp, updateDoc, where } from "firebase/firestore";
import type { DocumentData, QueryDocumentSnapshot } from "firebase/firestore";
import { auth, db } from "../firebase";
import { defaultActivityPlans, defaultBadgeworkPlans, newActivityPlan, newBadgeworkPlan } from "./weeklyTrackerLogic";
export { defaultActivityPlans, defaultBadgeworkPlans, newActivityPlan, newBadgeworkPlan } from "./weeklyTrackerLogic";

export type WeeklyAttendance = "present" | "absent" | "unrecorded";
export type WeeklyMeetingStatus = "open" | "closed";
export type InjurySeverity = "minor" | "moderate" | "serious";
export type WeeklyMemberEntry = { memberId: string; memberName: string; attendance: WeeklyAttendance; subsPaid: boolean; subsAmount: number; badges: string[] };
export type WeeklyInjury = { memberId: string; memberName: string; concern: string; severity: InjurySeverity; actionTaken: string; parentInformed: boolean; recordedAt: string };
export type WeeklyActivityPlan = { id: string; activity: string; leader: string; notes: string; equipment: string; startTime: string; finishTime: string };
export type WeeklyBadgeworkPlan = { id: string; badge: string; notes: string };
export type WeeklyMeetingRecord = { id: string; section: string; meetingDate: string; status: WeeklyMeetingStatus; location: string; theme: string; activities: WeeklyActivityPlan[]; badgeworkPlan: WeeklyBadgeworkPlan[]; programmeNotes: string; notes: string; entries: WeeklyMemberEntry[]; injuries: WeeklyInjury[] };
export type WeeklyMeetingInput = Omit<WeeklyMeetingRecord, "id">;
export type WeeklyAccess = { scoutingRole: string; canViewAll: boolean; canEditAll: boolean; readOnly: boolean };

const GROUP_SECTIONS = ["Beavers", "Cubs", "Scouts", "Ventures", "Rovers"];
const LEGACY_PLAN_MARKER = "weekly-plan-v1";
const ACTIVITY_MARKER = "weekly-activities-v1";
const BADGEWORK_MARKER = "weekly-badgework-v1";
const PROGRAMME_MARKER = "weekly-programme-v1";

function clean(value: string, max: number) { return value.trim().slice(0, max); }
function cleanEntry(entry: WeeklyMemberEntry): WeeklyMemberEntry { return { memberId: clean(entry.memberId,160), memberName: clean(entry.memberName,160), attendance: entry.attendance, subsPaid: entry.subsPaid === true, subsAmount: Number.isFinite(entry.subsAmount) ? Math.max(0,Math.min(1000,Number(entry.subsAmount.toFixed(2)))) : 0, badges: [...new Set(entry.badges.map((b)=>clean(b,120)).filter(Boolean))].slice(0,20) }; }
function cleanInjury(i: WeeklyInjury): WeeklyInjury { return { memberId: clean(i.memberId,160), memberName: clean(i.memberName,160), concern: clean(i.concern,2000), severity: ["minor","moderate","serious"].includes(i.severity) ? i.severity : "minor", actionTaken: clean(i.actionTaken,2000), parentInformed: i.parentInformed === true, recordedAt: clean(i.recordedAt,40) }; }
function cleanActivity(a: WeeklyActivityPlan): WeeklyActivityPlan { return { id: clean(a.id,100) || crypto.randomUUID(), activity: clean(a.activity,240), leader: clean(a.leader,160), notes: clean(a.notes,2000), equipment: clean(a.equipment,1000), startTime: clean(a.startTime,10), finishTime: clean(a.finishTime,10) }; }
function cleanBadgework(b: WeeklyBadgeworkPlan): WeeklyBadgeworkPlan { return { id: clean(b.id,100) || crypto.randomUUID(), badge: clean(b.badge,240), notes: clean(b.notes,2000) }; }
function cleanInput(input: WeeklyMeetingInput): WeeklyMeetingInput { return { section: clean(input.section,80), meetingDate: clean(input.meetingDate,20), status: input.status === "closed" ? "closed" : "open", location: clean(input.location,240), theme: clean(input.theme,240), activities: input.activities.map(cleanActivity).slice(0,30), badgeworkPlan: input.badgeworkPlan.map(cleanBadgework).slice(0,30), programmeNotes: clean(input.programmeNotes,4000), notes: clean(input.notes,4000), entries: input.entries.map(cleanEntry).filter((e)=>e.memberId&&e.memberName).slice(0,100), injuries: input.injuries.map(cleanInjury).filter((i)=>i.memberId&&i.memberName&&i.concern).slice(0,50) }; }
function mapEntry(value: unknown): WeeklyMemberEntry | null { if (!value || typeof value !== "object" || Array.isArray(value)) return null; const d=value as Record<string,unknown>; const memberId=typeof d.memberId==="string"?d.memberId.trim():""; const memberName=typeof d.memberName==="string"?d.memberName.trim():""; const attendance=d.attendance as WeeklyAttendance; if(!memberId||!memberName||!["present","absent","unrecorded"].includes(attendance)) return null; return { memberId, memberName, attendance, subsPaid:d.subsPaid===true, subsAmount:typeof d.subsAmount==="number"?d.subsAmount:0, badges:Array.isArray(d.badges)?d.badges.filter((x):x is string=>typeof x==="string"):[] }; }
function mapInjury(value: unknown): WeeklyInjury | null { if(!value||typeof value!=="object"||Array.isArray(value)) return null; const d=value as Record<string,unknown>; const memberId=typeof d.memberId==="string"?d.memberId.trim():""; const memberName=typeof d.memberName==="string"?d.memberName.trim():""; const concern=typeof d.concern==="string"?d.concern.trim():""; if(!memberId||!memberName||!concern) return null; const severity=d.severity as InjurySeverity; return { memberId, memberName, concern, severity:["minor","moderate","serious"].includes(severity)?severity:"minor", actionTaken:typeof d.actionTaken==="string"?d.actionTaken.trim():"", parentInformed:d.parentInformed===true, recordedAt:typeof d.recordedAt==="string"?d.recordedAt:"" }; }
function mapActivity(value: unknown, index: number): WeeklyActivityPlan | null { if(!value||typeof value!=="object"||Array.isArray(value))return null;const d=value as Record<string,unknown>;return { id:typeof d.id==="string"&&d.id?d.id:`activity-${index+1}`, activity:typeof d.activity==="string"?d.activity:"", leader:typeof d.leader==="string"?d.leader:"", notes:typeof d.notes==="string"?d.notes:"", equipment:typeof d.equipment==="string"?d.equipment:"", startTime:typeof d.startTime==="string"?d.startTime:"", finishTime:typeof d.finishTime==="string"?d.finishTime:"" }; }
function mapBadgework(value: unknown, index: number): WeeklyBadgeworkPlan | null { if(!value||typeof value!=="object"||Array.isArray(value))return null;const d=value as Record<string,unknown>;return { id:typeof d.id==="string"&&d.id?d.id:`badgework-${index+1}`, badge:typeof d.badge==="string"?d.badge:"", notes:typeof d.notes==="string"?d.notes:"" }; }
function decodeActivities(value: unknown): WeeklyActivityPlan[] { if(typeof value!=="string"||!value.trim())return[];try{const p=JSON.parse(value) as {marker?:unknown;items?:unknown};if(p.marker===ACTIVITY_MARKER&&Array.isArray(p.items))return p.items.map(mapActivity).filter((x):x is WeeklyActivityPlan=>x!==null);}catch{} return [{...newActivityPlan("legacy-activity-1"),activity:value.trim()}]; }
function decodeBadgework(value: unknown): WeeklyBadgeworkPlan[] { if(typeof value!=="string"||!value.trim())return[];try{const p=JSON.parse(value) as {marker?:unknown;items?:unknown};if(p.marker===BADGEWORK_MARKER&&Array.isArray(p.items))return p.items.map(mapBadgework).filter((x):x is WeeklyBadgeworkPlan=>x!==null);}catch{} return [{...newBadgeworkPlan("legacy-badgework-1"),badge:value.trim()}]; }
function decodeProgramme(value: unknown) { if(typeof value!=="string"||!value.trim())return {theme:"",programmeNotes:""};try{const p=JSON.parse(value) as Record<string,unknown>;if(p.marker===PROGRAMME_MARKER)return {theme:typeof p.theme==="string"?p.theme:"",programmeNotes:typeof p.notes==="string"?p.notes:""};}catch{} return {theme:"",programmeNotes:value.trim()}; }
function encodeActivities(items: WeeklyActivityPlan[]) { return JSON.stringify({ marker: ACTIVITY_MARKER, items }); }
function encodeBadgework(items: WeeklyBadgeworkPlan[]) { return JSON.stringify({ marker: BADGEWORK_MARKER, items }); }
function encodeProgramme(theme: string, notes: string) { return JSON.stringify({ marker: PROGRAMME_MARKER, theme, notes }); }
function legacyNotes(value: unknown) { const empty={ location:"", theme:"", plannedActivities:"", plannedBadgework:"", programmeNotes:"", notes:"" }; if(typeof value!=="string"||!value.trim()) return empty; try { const p=JSON.parse(value) as Record<string,unknown>; if(p.marker!==LEGACY_PLAN_MARKER) return {...empty,notes:value.trim()}; return { location:typeof p.location==="string"?p.location:"", theme:typeof p.theme==="string"?p.theme:"", plannedActivities:typeof p.plannedActivities==="string"?p.plannedActivities:"", plannedBadgework:typeof p.plannedBadgework==="string"?p.plannedBadgework:"", programmeNotes:typeof p.programmeNotes==="string"?p.programmeNotes:"", notes:typeof p.postMeetingNotes==="string"?p.postMeetingNotes:"" }; } catch { return {...empty,notes:value.trim()}; } }
function mapRecord(snapshot: QueryDocumentSnapshot<DocumentData>): WeeklyMeetingRecord | null { const data=snapshot.data(); const section=typeof data.section==="string"?data.section.trim():""; const meetingDate=typeof data.meetingDate==="string"?data.meetingDate.trim():""; if(!section||!meetingDate||!Array.isArray(data.entries)) return null; const entries=data.entries.map(mapEntry); if(entries.some((e)=>e===null)) return null; const legacy=legacyNotes(data.notes); const isStructured=typeof data.status==="string" || typeof data.location==="string" || Array.isArray(data.injuries); const activitySource=typeof data.plannedActivities==="string"?data.plannedActivities:legacy.plannedActivities; const badgeworkSource=typeof data.plannedBadgework==="string"?data.plannedBadgework:legacy.plannedBadgework; const programme=typeof data.programmeNotes==="string"?decodeProgramme(data.programmeNotes):{theme:legacy.theme,programmeNotes:legacy.programmeNotes}; return { id:snapshot.id, section, meetingDate, status:data.status==="open"?"open":"closed", location:typeof data.location==="string"?data.location.trim():legacy.location, theme:programme.theme||legacy.theme, activities:decodeActivities(activitySource), badgeworkPlan:decodeBadgework(badgeworkSource), programmeNotes:programme.programmeNotes||legacy.programmeNotes, notes:isStructured && typeof data.notes==="string"?data.notes.trim():legacy.notes, entries:entries as WeeklyMemberEntry[], injuries:Array.isArray(data.injuries)?data.injuries.map(mapInjury).filter((x):x is WeeklyInjury=>x!==null):[] }; }
function persisted(input: WeeklyMeetingInput) { const cleaned=cleanInput(input); return { section:cleaned.section,meetingDate:cleaned.meetingDate,status:cleaned.status,location:cleaned.location,plannedActivities:encodeActivities(cleaned.activities),plannedBadgework:encodeBadgework(cleaned.badgeworkPlan),programmeNotes:encodeProgramme(cleaned.theme,cleaned.programmeNotes),notes:cleaned.notes,entries:cleaned.entries,injuries:cleaned.injuries }; }

export async function loadWeeklyAccess(): Promise<WeeklyAccess> { const user=auth.currentUser; if(!user) return {scoutingRole:"",canViewAll:false,canEditAll:false,readOnly:false}; const snap=await getDoc(doc(db,"organisationLeadership",user.uid)); const role=snap.exists()&&typeof snap.data().scoutingRole==="string"?snap.data().scoutingRole:""; return { scoutingRole:role, canViewAll:["Group Leader","Group Secretary"].includes(role), canEditAll:role==="Group Leader", readOnly:role==="Group Secretary" }; }
export async function loadWeeklyMeetings(sections:string[],isAdmin:boolean,canViewAll=false):Promise<WeeklyMeetingRecord[]> { const requested=(isAdmin||canViewAll)?GROUP_SECTIONS:[...new Set(sections.map((s)=>s.trim()).filter(Boolean))]; if(!requested.length)return[]; const snapshots=await Promise.all(requested.map((section)=>getDocs(query(collection(db,"weeklyMeetings"),where("section","==",section))))); return snapshots.flatMap((s)=>s.docs).map(mapRecord).filter((r):r is WeeklyMeetingRecord=>r!==null).sort((a,b)=>b.meetingDate.localeCompare(a.meetingDate)); }
export async function createWeeklyMeeting(input:WeeklyMeetingInput):Promise<string>{ const user=auth.currentUser;if(!user)throw new Error("Leader authentication is required.");const result=await addDoc(collection(db,"weeklyMeetings"),{...persisted(input),createdBy:user.uid,createdAt:serverTimestamp(),updatedBy:user.uid,updatedAt:serverTimestamp()});return result.id; }
export async function updateWeeklyMeeting(id:string,input:WeeklyMeetingInput):Promise<void>{ const user=auth.currentUser;if(!user)throw new Error("Leader authentication is required.");await updateDoc(doc(db,"weeklyMeetings",id),{...persisted(input),updatedBy:user.uid,updatedAt:serverTimestamp()}); }
