import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableRow, Typography } from "@mui/material";
import type { ConsentAdminRecord } from "../../services/consentAdmin";
import { displayValue, formatDate, formatDateOnly, formatFieldName, objectField } from "../../services/consentManagementLogic";

function MedicationPanel({ value }: { value: Record<string, unknown> }) {
    const rows = [["Member",objectField(value,"memberName")],["Date of Birth",formatDateOnly(objectField(value,"dateOfBirth"))],["Address",objectField(value,"address")],["Medicine",objectField(value,"medicineName")],["Dosage",objectField(value,"dosage")],["Frequency",objectField(value,"frequency")],["Method",objectField(value,"method")],["Quantity Supplied",objectField(value,"quantitySupplied")],["Self Administration",objectField(value,"selfAdmin")],["Authorised From",formatDateOnly(objectField(value,"authFrom"))],["Authorised Until",formatDateOnly(objectField(value,"authTo"))],["Doctor",objectField(value,"doctorName")],["Doctor Telephone",objectField(value,"doctorTel")],["Pharmacy",objectField(value,"pharmacyName")],["Pharmacy Telephone",objectField(value,"pharmacyTel")],["Scouter 1",objectField(value,"scouter1")],["Scouter 2",objectField(value,"scouter2")],["Additional Information",objectField(value,"otherInfo")],["Signed By",objectField(value,"signature")],["Signature Date",formatDateOnly(objectField(value,"signatureDate"))]];
    return <Paper variant="outlined" sx={{gridColumn:{xs:"1",md:"1 / -1"},overflow:"hidden",borderWidth:2,borderColor:"error.light"}}><Box sx={{px:3,py:2,borderBottom:"1px solid",borderColor:"error.light"}}><Stack direction="row" spacing={1} sx={{alignItems:"center",flexWrap:"wrap"}}><Typography variant="h5" color="error.main" sx={{fontWeight:800}}>Medication Management</Typography><Chip label="SIF 20/10" color="error" size="small"/></Stack></Box><TableContainer><Table size="small"><TableBody>{rows.map(([label,text])=><TableRow key={label}><TableCell sx={{width:"38%",fontWeight:700,color:"secondary.main",verticalAlign:"top"}}>{label}</TableCell><TableCell>{text||"Not provided"}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Paper>;
}

export default function ConsentDetailDialog({ record, onClose, onPrint }: { record: ConsentAdminRecord | null; onClose: () => void; onPrint: (record: ConsentAdminRecord) => void; }) {
    return <Dialog open={Boolean(record)} onClose={onClose} maxWidth="lg" fullWidth>{record&&<><DialogTitle>Consent Record — {record.memberName}</DialogTitle><DialogContent dividers><Stack direction="row" spacing={1} sx={{flexWrap:"wrap",rowGap:1,mb:3}}><Chip label={record.type==="youth"?"Youth Consent":"Scouter ES3"} color="secondary"/>{record.section&&<Chip label={record.section} variant="outlined"/>}{record.type==="youth"&&!record.memberId&&<Chip label="Not linked to member" color="warning"/>}{record.updatedByParent&&<Chip label="Updated by parent" color="success"/>}{record.hasMedicalAlert&&<Chip label="Medical information present" color="warning"/>}{record.hasMedicationManagement&&<Chip label="Medication management required" color="error"/>}</Stack>{record.updatedByParent&&<Alert severity="success" sx={{mb:2}}>This record was updated through the Parent Portal on {formatDate(record.parentUpdatedAt||record.updatedAt)}.</Alert>}{record.type==="youth"&&!record.memberId&&<Alert severity="warning" sx={{mb:2}}>This youth consent record is not linked to a member ID. Re-save the parent’s approved Parent Access links to match it before Parent Portal editing can be used.</Alert>}<Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr 1fr"},gap:2}}>{Object.entries(record.data).filter(([key])=>key!=="submittedAt"&&key!=="authorisedScouters").map(([key,value])=>{ if(key==="medicationManagement"&&value&&typeof value==="object"&&!Array.isArray(value)&&(value as Record<string,unknown>).enabled===true) return <MedicationPanel key={key} value={value as Record<string,unknown>}/>; const text=displayValue(value); if(!text)return null; return <Paper key={key} variant="outlined" sx={{p:2,gridColumn:typeof value==="object"&&value!==null?{md:"1 / -1"}:undefined}}><Typography variant="caption" color="text.secondary" sx={{fontWeight:700}}>{formatFieldName(key)}</Typography><Typography sx={{mt:.5,whiteSpace:"pre-wrap",wordBreak:"break-word"}}>{text}</Typography></Paper>;})}</Box></DialogContent><DialogActions><Button onClick={()=>onPrint(record)}>Print / Save PDF</Button><Button onClick={onClose}>Close</Button></DialogActions></>}</Dialog>;
}
