import { Alert, Box, Button, Chip, CircularProgress, FormControl, InputLabel, MenuItem, Paper, Select, Stack, TextField, Typography } from "@mui/material";
import { daysUntilExpiry, isConsentExpired } from "../../services/consentAdmin";
import type { ConsentAdminRecord } from "../../services/consentAdmin";
import { CONSENT_SECTIONS, activeSummaryFilter, consentTotals, expiryLabel, formatDate, filtersForSummary } from "../../services/consentManagementLogic";
import type { AlertFilter, SummaryFilter, TypeFilter } from "../../services/consentManagementLogic";
import { moveToUiTargetAfterRender } from "../../services/uiTargeting";

export default function ConsentOverviewPanel({ records, filteredRecords, loading, search, typeFilter, sectionFilter, alertFilter, onSearchChange, onTypeFilterChange, onSectionFilterChange, onAlertFilterChange, onView, onPrint }: { records: ConsentAdminRecord[]; filteredRecords: ConsentAdminRecord[]; loading: boolean; search: string; typeFilter: TypeFilter; sectionFilter: string; alertFilter: AlertFilter; onSearchChange: (value: string) => void; onTypeFilterChange: (value: TypeFilter) => void; onSectionFilterChange: (value: string) => void; onAlertFilterChange: (value: AlertFilter) => void; onView: (record: ConsentAdminRecord) => void; onPrint: (record: ConsentAdminRecord) => void; }) {
    const totals = consentTotals(records);
    const active = activeSummaryFilter(typeFilter, alertFilter);
    const cards: Array<[string, number, SummaryFilter]> = [["Total", totals.total, "total"], ["Youth", totals.youth, "youth"], ["Scouters", totals.scouter, "scouter"], ["Medication", totals.medication, "medication"], ["Medical Alerts", totals.medical, "medical"], ["Expired", totals.expired, "expired"]];
    const apply = (filter: SummaryFilter) => {
        const next = filtersForSummary(filter);
        onTypeFilterChange(next.typeFilter);
        onAlertFilterChange(next.alertFilter);
        moveToUiTargetAfterRender("consent-results", { focus: true });
    };

    return <>
        <Box role="group" aria-label="Consent summary filters" sx={{ display: "grid", gridTemplateColumns: { xs: "1fr 1fr", md: "repeat(6,1fr)" }, gap: 2, mb: 3 }}>{cards.map(([label,value,filter]) => <Paper key={filter} variant="outlined" role="button" tabIndex={0} aria-pressed={active===filter} aria-controls="consent-results" onClick={() => apply(filter)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); apply(filter); } }} sx={{ p:2.5,textAlign:"center",cursor:"pointer",borderWidth:active===filter?2:1,borderColor:active===filter?"secondary.main":"divider","&:focus-visible":{outline:"3px solid",outlineColor:"secondary.main",outlineOffset:2} }}><Typography variant="h4" color="secondary">{value}</Typography><Typography variant="body2" color="text.secondary">{label}</Typography></Paper>)}</Box>
        <Paper elevation={2} sx={{p:3,mb:3}}><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"2fr 1fr 1fr 1fr"},gap:2}}>
            <TextField label="Search consent records" value={search} onChange={(e)=>onSearchChange(e.target.value)} placeholder="Name, section, medical information..." />
            <FormControl><InputLabel>Form type</InputLabel><Select label="Form type" value={typeFilter} onChange={(e)=>onTypeFilterChange(e.target.value as TypeFilter)}><MenuItem value="all">All</MenuItem><MenuItem value="youth">Youth</MenuItem><MenuItem value="scouter">Scouter ES3</MenuItem></Select></FormControl>
            <FormControl><InputLabel>Section</InputLabel><Select label="Section" value={sectionFilter} onChange={(e)=>onSectionFilterChange(e.target.value)}>{CONSENT_SECTIONS.map((section)=><MenuItem key={section} value={section}>{section==="all"?"All sections":section}</MenuItem>)}</Select></FormControl>
            <FormControl><InputLabel>Attention</InputLabel><Select label="Attention" value={alertFilter} onChange={(e)=>onAlertFilterChange(e.target.value as AlertFilter)}><MenuItem value="all">All</MenuItem><MenuItem value="medical">Medical alerts</MenuItem><MenuItem value="medication">Medication management</MenuItem><MenuItem value="expiring">Expires in 30 days</MenuItem><MenuItem value="expired">Expired</MenuItem></Select></FormControl>
        </Box></Paper>
        <Box id="consent-results" role="region" aria-label="Consent results" tabIndex={-1}>
            {loading ? <Box sx={{minHeight:300,display:"flex",justifyContent:"center",alignItems:"center"}}><CircularProgress color="success" /></Box> : <Box sx={{display:"grid",gap:2}}>{filteredRecords.length===0&&<Alert severity="info">No consent records match the current filters.</Alert>}{filteredRecords.map((record)=>{ const expired=isConsentExpired(record.consentTo); const days=daysUntilExpiry(record.consentTo); const soon=days!==null&&days>=0&&days<=30; return <Paper key={record.id} variant="outlined" sx={{p:2.5,borderLeft:record.hasMedicationManagement?"6px solid":undefined,borderLeftColor:record.hasMedicationManagement?"error.main":undefined}}><Box sx={{display:"flex",flexDirection:{xs:"column",lg:"row"},justifyContent:"space-between",gap:2}}><Box><Stack direction="row" spacing={1} useFlexGap sx={{flexWrap:"wrap",alignItems:"center"}}><Typography variant="h5" color="secondary">{record.memberName}</Typography><Chip size="small" label={record.type==="youth"?"Youth":"Scouter ES3"} color={record.type==="youth"?"primary":"secondary"}/>{record.section&&<Chip size="small" variant="outlined" label={record.section}/>} {record.type==="youth"&&!record.memberId&&<Chip size="small" color="warning" label="Not linked to member"/>}{record.updatedByParent&&<Chip size="small" color="success" label="Updated by parent"/>}{record.hasMedicalAlert&&<Chip size="small" color="warning" label="Medical"/>}{record.hasMedicationManagement&&<Chip size="small" color="error" label="Medication"/>}{expired&&<Chip size="small" color="error" label="Expired"/>}{!expired&&soon&&<Chip size="small" color="warning" label="Expiring soon"/>}</Stack><Typography color="text.secondary" sx={{mt:1}}>Submitted {formatDate(record.submittedAt)}</Typography>{record.consentTo&&<Typography variant="body2" color={expired?"error.main":soon?"warning.main":"text.secondary"} sx={{mt:.5,fontWeight:expired||soon?700:400}}>{expiryLabel(record)}</Typography>}</Box><Stack direction={{xs:"column",sm:"row"}} spacing={1.5}><Button variant="outlined" color="secondary" onClick={()=>onPrint(record)}>Print</Button><Button variant="contained" color="success" onClick={()=>onView(record)}>View Details</Button></Stack></Box></Paper>;})}</Box>}
        </Box>
    </>;
}
