import { Alert, Box, Button, Chip, CircularProgress, Container, Dialog, DialogActions, DialogContent, DialogTitle, Paper, Stack, TextField, Typography } from "@mui/material";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useAdminAuth } from "../components/admin/AdminAuthProvider";
import { approveLeaderRegistration, loadLeaderRegistrationRequests, rejectLeaderRegistration } from "../services/leaderRegistrations";
import type { LeaderRegistrationRequest } from "../services/leaderRegistrations";
function formatDate(value: Date | null) { if (!value) return "Unknown date"; return new Intl.DateTimeFormat("en-IE", { dateStyle: "medium", timeStyle: "short" }).format(value); }
export default function LeaderRequests() {
 const { user, adminProfile } = useAdminAuth(); const [requests,setRequests]=useState<LeaderRegistrationRequest[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [search,setSearch]=useState(""); const [selected,setSelected]=useState<LeaderRegistrationRequest|null>(null); const [reviewNote,setReviewNote]=useState(""); const [saving,setSaving]=useState(false);
 const refresh=async()=>{setLoading(true);setError("");try{setRequests(await loadLeaderRegistrationRequests());}catch(err){console.error(err);setError("Unable to load leader registration requests.");}finally{setLoading(false);}}; useEffect(()=>{void refresh();},[]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return !q?requests:requests.filter(r=>[r.fullName,r.email,r.mobileNumber,r.requestedRole,r.requestedSection,r.status].join(" ").toLowerCase().includes(q));},[requests,search]);
 const finish=async(approved:boolean)=>{if(!selected||!user)return;setSaving(true);try{if(approved)await approveLeaderRegistration(selected,user.uid,reviewNote);else await rejectLeaderRegistration(selected.uid,user.uid,reviewNote);setSelected(null);setReviewNote("");await refresh();}catch(err){console.error(err);setError("Unable to review this leader request.");}finally{setSaving(false);}};
 if(!adminProfile||!["admin","super-admin"].includes(adminProfile.role))return <Container maxWidth="md" sx={{py:6}}><Alert severity="error">Administrator access is required to review leader registrations.</Alert></Container>;
 return <Box sx={{minHeight:"100vh",backgroundColor:"background.default",py:{xs:4,md:6}}}><Container maxWidth="lg"><Paper elevation={2} sx={{p:{xs:2.5,md:4},mb:3}}><Box sx={{display:"flex",gap:2,flexWrap:"wrap",justifyContent:"space-between"}}><Box><Typography variant="h3" color="secondary">Leader Registration Requests</Typography><Typography color="text.secondary">Approve new leaders. Approved users start as section-scoped Leaders; use Leader Access afterwards to change their sections or role.</Typography></Box><Button component={Link} to="/leader/access" variant="outlined">Leader Access</Button></Box></Paper><TextField fullWidth label="Search requests" value={search} onChange={e=>setSearch(e.target.value)} sx={{mb:2}} />{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{loading?<CircularProgress/>:<Stack spacing={2}>{visible.map(r=><Paper key={r.uid} variant="outlined" sx={{p:2.5}}><Box sx={{display:"flex",justifyContent:"space-between",gap:2,flexWrap:"wrap"}}><Box><Typography variant="h6">{r.fullName}</Typography><Typography color="text.secondary">{r.email} · {r.requestedRole} · {r.requestedSection}</Typography><Typography variant="body2">Submitted {formatDate(r.submittedAt)}</Typography></Box><Chip label={r.status}/></Box>{r.status==="pending"&&<Button sx={{mt:2}} variant="contained" onClick={()=>setSelected(r)}>Review</Button>}</Paper>)}</Stack>}
 <Dialog open={Boolean(selected)} onClose={()=>setSelected(null)} fullWidth><DialogTitle>Review leader request</DialogTitle><DialogContent><TextField fullWidth multiline minRows={3} label="Review note" value={reviewNote} onChange={e=>setReviewNote(e.target.value)} sx={{mt:1}} /></DialogContent><DialogActions><Button onClick={()=>void finish(false)} disabled={saving}>Reject</Button><Button variant="contained" onClick={()=>void finish(true)} disabled={saving}>Approve as Leader</Button></DialogActions></Dialog></Container></Box>;
}
