import LeaderDashboardHeader from "../components/admin/LeaderDashboardHeader";
import LeaderPageHeader from "../components/admin/LeaderPageHeader";
import OrganisationChartContent from "../components/admin/OrganisationChartContent";
import { Accordion, AccordionDetails, AccordionSummary, Alert, Box, Chip, Container, Paper, Stack, Typography } from "@mui/material";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";

type StageStatus = "Complete" | "Current" | "Planned";
type Stage = { number: string; title: string; status: StageStatus; summary: string; };

const stages: Stage[] = [
  { number: "1", title: "Public Website & Join Us", status: "Complete", summary: "Public website, joining enquiries, waiting-list management and conversion of accepted enquiries into member records." },
  { number: "2", title: "Consent & Parent Access", status: "Complete", summary: "Youth consent, Scouter ES3, medication management, parent accounts, linked children and parent consent updates." },
  { number: "3", title: "Leader Portal & Roles", status: "Complete", summary: "Leader registration, approval, profiles, section-scoped permissions, Group roles and the public Who’s Who opt-in." },
  { number: "4", title: "Members & Organisation", status: "Complete", summary: "Member management, section moves, member history, parent links, organisation chart and role-based access." },
  { number: "5", title: "Events & Communications", status: "Complete", summary: "Events, camps and trips, parent event consent, attendance, communications, reports and exports." },
  { number: "6", title: "Weekly Meetings", status: "Complete", summary: "Create, open, save, close and copy section meetings with fast attendance, flexible programme planning, badgework, incidents and meeting history." },
  { number: "7", title: "Meeting Records & Reporting", status: "Complete", summary: "Leader and Group Council meeting records, all-section history for authorised Group roles, attendance insights, activity logs and operational reporting." },
  { number: "8", title: "Production Hardening & Continuous Improvement", status: "Complete", summary: "Hosting security and privacy guards, audit-log integrity, live-data/schema compatibility, accessibility coverage, dependency maintenance, backup/recovery, route code-splitting, application error recovery, CI cleanup and Firestore read-efficiency safeguards." },
  { number: "9", title: "Workflow, Consent & Usability Improvements", status: "Complete", summary: "Searchable member and attendance history, improved navigation and mobile meeting editing, richer Weekly Meetings and WhatsApp sharing, Meeting Records import/version history, direct event-consent workflows, searchable Parent Portal consent, expanded reporting and broader read-only Group officer activity auditing." },
  { number: "10", title: "Programme, Events & Insights", status: "Complete", summary: "Combined meeting/event attendance insights, reusable programme-library items, date-filtered reports and trends, stricter event close-out, actionable Parent Portal tasks, mobile/accessibility regression coverage and production-safe Firestore read optimisation." },
  { number: "11", title: "Architecture, UX & Operational Hardening", status: "Complete", summary: "Leader dashboard and reporting improvements, shared Scout-year periods, Programme Library discovery, route decomposition for major operational pages, configurable inactivity sign-out and stricter historical meeting editing with attendance terminology aligned across meetings and events." },
  { number: "12", title: "Adventure Skills & Badgework Tracking", status: "Complete", summary: "Canonical Scouting Ireland Adventure Skills and Swimming competency tracking, two-step multi-member badgework entry with explicit Save, shared competency propagation, member-owned progress across section moves, separate badge awards, completion provenance, Weekly Meeting and event/activity handoffs, parent read-only stage detail and Playwright regression coverage." },
  { number: "13", title: "Equipment & Stores", status: "Complete", summary: "Group equipment inventory, checkout and return, broken/lost/missing reporting and resolution, immutable equipment history and stock movements, programme planning and reservations, CSV reporting, role-based permissions and final regression/seed/documentation close-out." }
];

const faqs = [
  { q: "Where are members stored?", a: "Member records are stored in Firestore. Use Member Management for the current record and Member History for retained lifecycle history." },
  { q: "How are members created?", a: "Accepted Join Us enquiries can be converted into member records, and authorised leaders can also add existing members manually from Member Management." },
  { q: "Can leaders move members between sections or change their status?", a: "Yes. Authorised leaders can move members between sections and set their status to Active, Inactive or Left. Relevant history is retained." },
  { q: "How does parent access work?", a: "Parent accounts are approved separately and linked to the correct children. Leaders can search for a child when managing links rather than loading the full member list." },
  { q: "How are consent and medical details handled?", a: "Member Management shows useful consent, medical, medication and expiry indicators. Full consent and medical details remain in the restricted consent-management areas. Approved parents can use the searchable Consent area in the Parent Portal for their linked children." },
  { q: "How does event consent work?", a: "For an open event that requires consent, leaders can open Manage Consent directly from that event. Parents use the tokenised consent flow, while authorised leaders can review and match responses and see consent state in Attendance." },
  { q: "What happens if an event-consent response cannot be matched?", a: "It remains visible as unmatched. An authorised leader can match it to the correct member or ignore a duplicate or test response." },
  { q: "What happens when an event is completed?", a: "Events move deliberately through Draft, Open, Closed and Completed. Completion requires resolved attendance and, when consent is required, no outstanding consent for members still attending. Completed events remain read-only history for reporting and review." },
  { q: "How do weekly meetings work?", a: "Weekly Meetings starts with Create Meeting, Open Meeting and Meeting History. Future meetings open into Programme for planning. A meeting can be saved without leaving the editor and closed when finished. Closed meetings remain historical records: authorised senior roles can make limited corrections, but programme planning and completed badgework stay locked." },
  { q: "How do I take attendance at a weekly meeting?", a: "Attendance uses large present checkboxes for quick roll call. Mark all present can select the visible roster at once, and unchecked members are recorded as absent when attendance is saved." },
  { q: "What can I plan in a weekly meeting?", a: "The planner supports a theme, programme notes, flexible activity/game rows and planned badgework. Activity and badgework rows can include assigned leaders, instructions or notes, equipment and a duration in minutes. Structured Equipment & Stores requirements can also be planned, reserved and checked out for the meeting. A warning is shown when planned programme time exceeds 90 minutes." },
  { q: "What is the Programme Library?", a: "Leaders can save reusable activity/game and badgework rows to the section-scoped Programme Library and insert them into another Weekly Meeting. The library is searchable and filterable by item type and duration. Each insertion creates a fresh meeting item; attendance, incidents, completed badgework and post-meeting notes are never carried across." },
  { q: "What is the meeting summary?", a: "While editing a Weekly Meeting, the summary shows the current activity count, badgework count, planned duration, attendance, incidents, location and theme so the leader can quickly review the meeting before or after saving." },
  { q: "Can I share a weekly meeting in WhatsApp?", a: "Yes. The WhatsApp share contains the parent-safe meeting programme, including activities, badgework and parent-safe equipment wording. It does not include leader-only attendance, equipment stock internals, incidents or internal notes." },
  { q: "Can I copy a meeting for next week?", a: "Yes. Copy Meeting creates a new open meeting; it never overwrites the original. You can use today or choose another date. Reusable programme structure and planned equipment requirements are copied, while attendance, completed badgework, injuries/medical incidents, post-meeting notes, equipment reservations and checkout transactions are reset." },
  { q: "Can I copy a closed meeting from Meeting History?", a: "Yes. Meeting History can be used as a source for Copy Meeting, which is useful for reusing a successful programme as a template without changing the original historical meeting." },
  { q: "What can be edited in a past weekly meeting?", a: "Only Section Leader roles and above can edit a closed weekly meeting. Those edits are limited to attendance, injuries/medical issues and additional notes. Programme planning, planned or completed badgework and meeting status remain locked. Assistant Section Leaders, Programme Scouters, Scouters and Group Secretaries remain view-only for closed meetings." },
  { q: "Who can see or edit weekly meetings?", a: "Section leaders work within their assigned sections. The Group Leader can work across sections, the Group Secretary has all-section weekly meeting history access without historical editing rights, and administrators retain their authorised management access. Copying a closed meeting is still available where normal meeting-edit access allows it because the copy creates a new meeting rather than changing history." },
  { q: "How does Adventure Skills badgework work?", a: "Badgework uses the canonical Scouting Ireland Adventure Skills competency statements: the nine handbook skills have stages 1–9 and Swimming has stages 1–6. Leaders first select one or more children, continue to the badgework step, choose a skill and stage, mark individual competency points or the full stage, then explicitly Save changes." },
  { q: "What happens when the same competency appears in more than one Adventure Skill?", a: "Only explicitly equivalent shared competencies are linked. Completing a linked competency once credits the matching competency in the other linked skills. For example, the matching Stage 1 Buddy System points are shared where the source statements represent the same expectation; similar but broader statements are not automatically treated as equivalent." },
  { q: "Does Adventure Skills progress move with a child when they change section?", a: "Yes. Adventure Skills progress belongs to the member record rather than to a section, so completed competencies and awards remain with the child after a section move. Access is still checked against the child’s current section and the leader’s authorised scope." },
  { q: "Are completing a stage and awarding the badge the same thing?", a: "No. Requirements complete and Awarded are deliberately separate states. A badge can only be awarded after the selected child or children have all persisted requirements complete for that stage, and an award can be removed without deleting the competency completion history." },
  { q: "Can badgework be recorded from Weekly Meetings and events or activities?", a: "Yes. Open Weekly Meetings and event/activity attendance can hand the relevant children into Badgework. The leader still confirms the selected children before entering badgework. Saved competency records retain source context so a single-child leader view can show when and where the completion was recorded. Closed Weekly Meetings cannot use this route to change historical completed badgework." },
  { q: "What can parents see about Adventure Skills?", a: "Approved parents can see read-only Adventure Skills progress for their linked children. Each skill shows completed competency totals and awarded stages, and each stage can be expanded to show every competency as Completed or Outstanding. Parents cannot edit competency completion or award badges, and leader/source provenance is not exposed in the Parent Portal." },
  { q: "What is Equipment & Stores?", a: "Equipment & Stores is the group equipment register. It tracks stock quantities, categories, storage locations, current section holdings, unavailable stock, incidents, immutable equipment history, programme requirements/reservations and equipment reports." },
  { q: "Who can manage equipment?", a: "The Group Quartermaster / Bo’sun, Group Leader and administrator roles can manage the full group inventory, move stock, investigate and resolve incidents and export equipment reports. Active leaders can view the catalogue and history, check equipment in or out for their authorised sections and report issues connected to their section holdings. Parents have no access to internal equipment stock, loans, reservations, incidents or history." },
  { q: "How do equipment checkout and returns work?", a: "A checkout records the section, equipment quantities and expected return date. Availability is checked transactionally so the same remaining stock cannot be successfully allocated twice. Current Section Holdings shows open equipment, and partial or full returns update both the loan and live stock availability." },
  { q: "How are broken, lost, missing or maintenance issues handled?", a: "Leaders can report Damaged, Lost, Missing or Maintenance/Cleaning issues. Affected stock becomes unavailable. Damaged, lost and missing reports use the urgent notification path for equipment managers. The Quartermaster / Bo’sun, Group Leader or administrator can move an issue through Reported, Investigating and Resolved and record outcomes such as found/returned, repaired, replaced, written off or no action required." },
  { q: "What does equipment history record?", a: "Equipment history is append-only and records operational changes such as checkouts, returns, incidents, resolutions and stock movements. Equipment managers can move available stock between storage locations; partial movements retain the remaining quantity at the source and create or add the moved quantity at the destination." },
  { q: "Can meetings, events and activities reserve equipment?", a: "Yes. Weekly Meetings and Events & Activities can add structured planned equipment requirements. Planning alone does not allocate stock. A leader can reserve the requirement for the programme date and later convert it to a real checkout. Statuses progress through Planned, Reserved, Checked Out, Partially Returned and Returned." },
  { q: "What equipment reports are available?", a: "Equipment & Stores can export Inventory Summary, Equipment by Location, Equipment by Category, Current Section Holdings, Overdue Equipment, Repair / Maintenance List, Missing / Lost Equipment, Loss & Damage History, Equipment Usage and Write-offs / Replacement Value. Filters include section, equipment item, category, location, status/issue and date range where relevant. Equipment managers also have an Export all equipment CSV button on the dashboard." },
  { q: "What are Meeting Records for?", a: "Meeting Records are for formal leader, Group Council and Group Leaders meeting notes, decisions and actions. They are separate from Weekly Meetings, which track the youth-section programme and attendance." },
  { q: "Can Meeting Records be imported from a document?", a: "Yes. Text, Markdown and HTML meeting notes can be imported into a reviewable draft. The title, type, section, date/time, attendees, minutes, decisions and actions can then be corrected before Save Meeting is pressed." },
  { q: "Are previous versions of Meeting Records retained?", a: "Yes. Editing a Meeting Record retains the pre-edit version in read-only Version History so authorised users can inspect the earlier minutes, attendees, decisions and actions." },
  { q: "Who can see Group and section meeting history?", a: "Access is role-based. Group Leader and Group Secretary roles can view the broader meeting history needed for their roles, while section leaders remain scoped to their permitted sections." },
  { q: "Where can I see attendance trends?", a: "Attendance Insights provides separate Weekly Meeting, Event and Combined recorded-attendance rates, recent attendance across both sources, inclusive date-range filtering and per-member detail. Unrecorded attendance is excluded from the rate denominator. Scout-year and Autumn, Spring and Summer term presets are also available." },
  { q: "What reports are available?", a: "Reports & Exports includes member lists, membership summaries, date-filtered event overviews, attendance-trend exports, event attendance/consent data, outstanding-consent reporting and a print-friendly operational summary, all limited to the leader’s permitted scope. Equipment & Stores has its own operational stock and equipment-history report suite." },
  { q: "What does the Parent Portal show first?", a: "The Parent Portal summarises upcoming events and outstanding actions. When consent needs attention it highlights the earliest consent-required event as the next action; otherwise it highlights the next upcoming event." },
  { q: "How do Parent Communications and WhatsApp work?", a: "Compose the message first, then choose recipients for normal communications. Share via WhatsApp uses only the subject and leader-written message; it does not put selected parent names, email addresses, phone numbers or member IDs into the WhatsApp share URL." },
  { q: "Who can see the Activity Log?", a: "The Activity Log is read-only and available to Admin, Super Admin, Group Leader and Group Secretary roles. It records important administrative and leader actions, including Weekly Meeting create, update, close and copy actions. Entries cannot be edited or deleted from the website." },
  { q: "Why might I see fewer menu options than another leader?", a: "The Leader Portal is permission-aware. Available pages and actions depend on your approved access level, assigned sections and Scouting role." },
  { q: "Where is the organisational chart?", a: "The internal organisational chart is included on this Info & FAQ page so leaders can find organisational information and guidance in one place." },
  { q: "Where is Sign Out?", a: "Sign Out is the final action in the expandable Leader Menu, keeping the dashboard header compact on mobile." },
  { q: "How does automatic sign-out work?", a: "Authenticated sessions use session-only Firebase persistence, so closing the browser ends the authenticated browser session. Inactivity sign-out is also enforced: parent accounts default to 20 minutes on every device, while leader/admin accounts default to 20 minutes on desktop and 90 minutes on phones. Activity is synchronised across browser tabs, and elapsed inactivity is rechecked when a backgrounded tab becomes active again." },
  { q: "Can the inactivity limits be changed?", a: "Yes. Admin and Super Admin users can use Site Settings to configure the parent, leader desktop and leader phone inactivity limits. The application keeps safe defaults if the settings document has not yet been saved." },
  { q: "How is production data protected from schema drift?", a: "CI includes live Firestore provenance and compatibility checks for current collection contracts, including weekly meetings and meeting records. Safely migratable legacy shapes have dedicated reconcilers, while ambiguous or incompatible records remain blocking findings." },
  { q: "What happens if production Firestore is temporarily quota-exhausted during a pull request?", a: "Pull-request live-data auditing first probes production availability. If Firestore is quota-exhausted or unreachable, that live portion is explicitly deferred rather than producing a false application failure. Pushes to main and manual production audits still fail closed." },
  { q: "How are Firestore reads kept under control?", a: "High-read leader views use section-scoped queries, server-side aggregate counts where appropriate and short-lived caching for overview data. Reports reuse the member snapshot already loaded on the page for event exports rather than re-reading the same members. Production reseeding, reconciliation scans and speculative index changes are never run automatically." },
  { q: "What happens if a page crashes?", a: "The application has a top-level error boundary. Unexpected render failures show an accessible recovery screen with Reload page and Return home actions instead of leaving a blank application." },
  { q: "How is accessibility checked?", a: "Playwright includes an accessibility resilience baseline plus a Pixel 7 mobile close-out suite across representative public, parent and leader routes. Coverage includes semantic page structure, headings, named interactive controls, keyboard focus entry and horizontal-overflow detection." },
  { q: "How are backups handled?", a: "Firestore has a managed backup/export workflow and a documented recovery runbook. Operators should confirm a recent backup before major production changes or migrations." },
  { q: "How are dependencies kept secure?", a: "The Quality gate blocks high or critical vulnerabilities in production npm dependencies, and Dependabot provides grouped recurring maintenance updates. Secret-dependent workflows use a safe policy for Dependabot pull requests." },
  { q: "How is test data kept stable?", a: "Automated tests use canonical seeded records with stable identifiers and explicit seed-contract checks. The canonical Playwright seed is deliberately minimal. Equipment tests create transient stock, loans and incidents through the application during emulator-backed test runs instead of adding permanent equipment fixtures to the shared seed." },
  { q: "What was delivered in Stage 12?", a: "Stage 12 delivered the complete Adventure Skills and badgework tracker: canonical competency data, member-owned Firestore persistence and security rules, multi-member two-step entry with explicit Save, shared competency propagation, stage awards and provenance, Weekly Meeting and event/activity integration, read-only parent competency detail and end-to-end Playwright regression coverage." },
  { q: "What was delivered in Stage 13?", a: "Stage 13 delivered Equipment & Stores end to end: inventory and categories/locations, section checkout and return, incident reporting and resolution, immutable history and stock movement, Weekly Meeting and event/activity planning, reservations and checkout conversion, equipment reports and CSV exports, role-based Firestore permissions, final regression coverage and a minimal equipment seed contract." }
];

function chipColor(status: StageStatus): "success" | "warning" | "secondary" {
  if (status === "Complete") return "success";
  if (status === "Current") return "warning";
  return "secondary";
}

export default function LeaderInfo() {
  return (
    <Box sx={{ minHeight: "100vh", backgroundColor: "background.default", py: { xs: 4, md: 6 } }}>
      <Container maxWidth="xl">
        <LeaderDashboardHeader />
        <LeaderPageHeader title="Leader Portal Information" description="Current portal capabilities, organisational information, development status and frequently asked questions." />
        <Alert severity="success" sx={{ mb: 3 }}>
          Stages 1–13 are complete. Equipment & Stores now covers inventory, section holdings, incidents, stock history, programme reservations and reporting, with final regression coverage and a minimal deterministic equipment seed policy. Ongoing development should preserve the security, data-integrity, accessibility, recovery, seed-stability and Firestore read-efficiency safeguards already established.
        </Alert>

        <Typography variant="h4" color="secondary" sx={{ mb: 2, fontWeight: 800 }}>Organisational Chart</Typography>
        <Typography color="text.secondary" sx={{ mb: 2 }}>Internal organisational hierarchy, sections and reporting relationships for active leaders.</Typography>
        <Box sx={{ mb: 5 }}><OrganisationChartContent /></Box>

        <Typography variant="h4" color="secondary" sx={{ mb: 2, fontWeight: 800 }}>Development Roadmap</Typography>
        <Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", md: "1fr 1fr" }, gap: 2, mb: 5 }}>
          {stages.map((stage) => (
            <Paper key={stage.number} variant="outlined" sx={{ p: 2.5, borderRadius: 2, borderLeft: "5px solid", borderLeftColor: stage.status === "Current" ? "warning.main" : stage.status === "Complete" ? "success.main" : "secondary.main" }}>
              <Stack direction="row" spacing={1} sx={{ alignItems: "center", flexWrap: "wrap", rowGap: 1 }}>
                <Typography variant="h5" color="secondary" sx={{ fontWeight: 800 }}>Stage {stage.number}</Typography>
                <Chip label={stage.status} color={chipColor(stage.status)} size="small" variant={stage.status === "Planned" ? "outlined" : "filled"} />
              </Stack>
              <Typography variant="h6" sx={{ mt: 1.25, fontWeight: 700 }}>{stage.title}</Typography>
              <Typography color="text.secondary" sx={{ mt: 0.75 }}>{stage.summary}</Typography>
            </Paper>
          ))}
        </Box>

        <Typography variant="h4" color="secondary" sx={{ mb: 2, fontWeight: 800 }}>Frequently Asked Questions</Typography>
        <Paper variant="outlined" sx={{ borderRadius: 2, overflow: "hidden" }}>
          {faqs.map((faq, index) => (
            <Accordion key={faq.q} disableGutters elevation={0} sx={{ "&:before": { display: "none" }, borderBottom: index < faqs.length - 1 ? "1px solid" : "none", borderColor: "divider" }}>
              <AccordionSummary expandIcon={<ExpandMoreIcon />}><Typography sx={{ fontWeight: 700, color: "secondary.main" }}>{faq.q}</Typography></AccordionSummary>
              <AccordionDetails><Typography>{faq.a}</Typography></AccordionDetails>
            </Accordion>
          ))}
        </Paper>
      </Container>
    </Box>
  );
}
