import { Alert,Box,Button,Chip,Container,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,InputLabel,MenuItem,Paper,Select,Stack,Tab,Tabs,TextField,Typography } from "@mui/material";
import { useCallback,useEffect,useMemo,useState } from "react";
import LeaderDashboardHeader from "../components/admin/LeaderDashboardHeader";
import LeaderPageHeader from "../components/admin/LeaderPageHeader";
import { useAdminAuth } from "../components/admin/AdminAuthProvider";
import { isGroupLeadershipAppointment } from "../security/scoutingAppointments";
import { loadMembers,type MemberRecord } from "../services/memberAdmin";
import { loadSubsAssignments,loadSubsPayments,loadSubsPaymentsForAccount,loadSubsPolicies,recordSubsPayment,reverseSubsPayment } from "../services/subsLedger";
import { balanceFor,familyTypeLabel,formatEuro,parseEuroToCents,paymentMethodLabel,paymentsForAssignment,rateCategoryLabel,SUBS_PAYMENT_METHODS,type SubsAssignment,type SubsPayment,type SubsPaymentMethod,type SubsRatePolicy } from "../services/subsLogic";

const today=()=>new Date().toISOString().slice(0,10);
const csv=(rows:string[][])=>rows.map(row=>row.map(value=>`"${value.replaceAll('"','""')}"`).join(",")).join("\r\n");
const download=(name:string,body:string)=>{const url=URL.createObjectURL(new Blob([body],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);};
const uniquePayments=(rows:SubsPayment[])=>[...new Map(rows.map(row=>[row.id,row])).values()];

export default function SubsManagement(){
 const {adminProfile}=useAdminAuth();
 const canGroupReport=adminProfile?.role==="admin"||adminProfile?.role==="super-admin"||adminProfile?.scoutingRole==="Group Treasurer"||isGroupLeadershipAppointment(adminProfile?.scoutingRole);
 const [tab,setTab]=useState(0); const [members,setMembers]=useState<MemberRecord[]>([]); const [policies,setPolicies]=useState<SubsRatePolicy[]>([]); const [assignments,setAssignments]=useState<SubsAssignment[]>([]); const [payments,setPayments]=useState<SubsPayment[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [section,setSection]=useState("all");
 const [memberId,setMemberId]=useState(()=>new URLSearchParams(window.location.search).get("member")??""); const [period,setPeriod]=useState(""); const [amount,setAmount]=useState(""); const [method,setMethod]=useState<SubsPaymentMethod>("bank"); const [paymentDate,setPaymentDate]=useState(today()); const [note,setNote]=useState(""); const [saving,setSaving]=useState(false); const [confirmOpen,setConfirmOpen]=useState(false); const [correction,setCorrection]=useState<SubsPayment|null>(null); const [correctionReason,setCorrectionReason]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const scopedSections=adminProfile?.sections.filter(value=>value!=="Group")??[];const assignmentRows=canGroupReport?await loadSubsAssignments():(await Promise.all(scopedSections.map(value=>loadSubsAssignments(value)))).flat();const basePayments=canGroupReport?await loadSubsPayments():(await Promise.all(scopedSections.map(value=>loadSubsPayments(value)))).flat();const accountIds=[...new Set(assignmentRows.map(row=>row.accountId).filter((value):value is string=>Boolean(value)))];const accountPayments=canGroupReport?[]:(await Promise.all(accountIds.map(value=>loadSubsPaymentsForAccount(value)))).flat();const [m,p]=await Promise.all([loadMembers(),loadSubsPolicies()]);setMembers(m);setPolicies(p);setAssignments(assignmentRows);setPayments(uniquePayments([...basePayments,...accountPayments]));if(!period&&p[0])setPeriod(p[0].period);}catch(e){console.error(e);setError("Unable to load subs records.");}finally{setLoading(false);}},[adminProfile?.sections,canGroupReport,period]);
 useEffect(()=>{void load();},[]);
 const selected=members.find(m=>m.id===memberId); const selectedAssignment=assignments.find(a=>a.memberId===memberId&&a.period===period); const memberPayments=selectedAssignment?paymentsForAssignment(selectedAssignment,payments):[]; const selectedBalance=selectedAssignment?balanceFor(selectedAssignment,payments):null;
 const visibleAssignments=useMemo(()=>assignments.filter(a=>section==="all"||a.section===section).sort((a,b)=>a.memberName.localeCompare(b.memberName)),[assignments,section]); const sections=[...new Set(members.map(m=>m.section))].sort();
 const submitPayment=async()=>{if(!selected||!selectedAssignment)return setError("Select a member with a rate classification for this Scout year.");setSaving(true);setError("");try{await recordSubsPayment({memberId:selected.id,memberName:selected.displayName,section:selected.section,period,accountId:selectedAssignment.accountId,amountCents:parseEuroToCents(amount),method,paymentDate,note});setConfirmOpen(false);setAmount("");setNote("");setMessage(selectedAssignment.accountId?"Family subs payment recorded.":"Subs payment recorded.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to record payment.");}finally{setSaving(false);}};
 const reverse=async()=>{if(!correction)return;setSaving(true);try{await reverseSubsPayment(correction,correctionReason);setCorrection(null);setCorrectionReason("");setMessage("Payment correction recorded as a linked reversal.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to correct payment.");}finally{setSaving(false);}};
 const exportBalances=()=>download(`subs-balances-${section}-${period||"all"}.csv`,csv([["Member","Section","Scout year","Amount due (cents)","Amount paid (cents)","Remaining (cents)","Family classification","Child position","Rate category"],...visibleAssignments.filter(a=>!period||a.period===period).map(a=>{const b=balanceFor(a,payments);return[a.memberName,a.section,a.period,String(b.dueCents),String(b.paidCents),String(b.remainingCents),a.familyType?familyTypeLabel(a.familyType):"Legacy classification",a.familyPosition?String(a.familyPosition):"",rateCategoryLabel(a.category)];})]));
 const reviewPayment=()=>{try{parseEuroToCents(amount);setError("");setConfirmOpen(true);}catch(e){setError(e instanceof Error?e.message:"Enter a valid amount.");}};
 const exportMember=()=>{if(!selectedAssignment||!selectedBalance)return;download(`subs-${selectedAssignment.memberName}-${period}.csv`,csv([["Member","Section","Scout year","Rate category","Family classification","Child position","Amount due (cents)","Total paid (cents)","Remaining (cents)"],[selectedAssignment.memberName,selectedAssignment.section,period,rateCategoryLabel(selectedAssignment.category),selectedAssignment.familyType?familyTypeLabel(selectedAssignment.familyType):"Legacy classification",selectedAssignment.familyPosition?String(selectedAssignment.familyPosition):"",String(selectedBalance.dueCents),String(selectedBalance.paidCents),String(selectedBalance.remainingCents)],[],["Payment date","Method","Amount (cents)","Correction of","Note"],...memberPayments.map(p=>[p.paymentDate,paymentMethodLabel(p.method),String(p.amountCents),p.reversalOfPaymentId,p.note])]));};
 if(loading)return <Container><LeaderDashboardHeader/><Typography>Loading subs records…</Typography></Container>;
 return <Box sx={{minHeight:"100vh",backgroundColor:"background.default",py:{xs:4,md:6}}}><Container maxWidth="xl"><LeaderDashboardHeader/><LeaderPageHeader title="Scout Subs" description="Record auditable payments and review Scout-year balances. Family classifications are managed from Settings by the Treasurer, Group Leader, Deputy Group Leader and admins."/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{message&&<Alert severity="success" sx={{mb:2}}>{message}</Alert>}
 <Paper sx={{mb:3}}><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" aria-label="Subs management sections"><Tab label="Record payment"/><Tab label="Balances & reports"/></Tabs></Paper>
 {tab===0&&<Paper sx={{p:{xs:2,md:3}}}><Typography variant="h5" sx={{fontWeight:800,mb:2}}>Record a payment</Typography><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(2,1fr)"},gap:2}}><FormControl required><InputLabel id="subs-member-label">Member</InputLabel><Select labelId="subs-member-label" label="Member" value={memberId} onChange={e=>setMemberId(e.target.value)} data-testid="subs-member-select">{members.map(m=><MenuItem key={m.id} value={m.id}>{m.displayName} · {m.section}</MenuItem>)}</Select></FormControl><FormControl required><InputLabel id="subs-period-label">Scout year</InputLabel><Select labelId="subs-period-label" label="Scout year" value={period} onChange={e=>setPeriod(e.target.value)}>{policies.map(p=><MenuItem key={p.id} value={p.period}>{p.period}</MenuItem>)}</Select></FormControl><TextField required label="Amount (EUR)" value={amount} onChange={e=>setAmount(e.target.value)} slotProps={{htmlInput:{inputMode:"decimal"}}}/><FormControl required><InputLabel id="subs-method-label">Payment method</InputLabel><Select labelId="subs-method-label" label="Payment method" value={method} onChange={e=>setMethod(e.target.value as SubsPaymentMethod)}>{SUBS_PAYMENT_METHODS.map(m=><MenuItem key={m} value={m}>{paymentMethodLabel(m)}</MenuItem>)}</Select></FormControl><TextField required type="date" label="Payment date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField label="Note (optional)" value={note} onChange={e=>setNote(e.target.value)} slotProps={{htmlInput:{maxLength:200}}}/></Box>{selectedAssignment&&selectedBalance?<><Stack direction={{xs:"column",sm:"row"}} spacing={1} sx={{mt:2,flexWrap:"wrap"}}><Chip label={`Due ${formatEuro(selectedBalance.dueCents)}`}/><Chip label={`Paid ${formatEuro(selectedBalance.paidCents)}`}/><Chip label={selectedBalance.remainingCents<0?`Credit ${formatEuro(-selectedBalance.remainingCents)}`:`Remaining ${formatEuro(selectedBalance.remainingCents)}`}/><Chip label={selectedAssignment.accountId?`Shared ${selectedAssignment.accountChildCount}-member family account`:selectedAssignment.familyType&&selectedAssignment.familyPosition?`${familyTypeLabel(selectedAssignment.familyType)} · member ${selectedAssignment.familyPosition}`:rateCategoryLabel(selectedAssignment.category)}/></Stack>{selectedAssignment.accountId&&<Alert severity="info" sx={{mt:2}} data-testid="subs-shared-family-balance">This is the shared family balance for the Scout year. Payments recorded through any member in this family reduce the same balance.</Alert>}</>:memberId&&<Alert severity="warning" sx={{mt:2}}>This member needs an authorized rate classification for the selected Scout year before payment can be recorded.</Alert>}<Button variant="contained" sx={{mt:3,minHeight:44}} disabled={saving||!selectedAssignment||!amount} onClick={reviewPayment}>Review payment</Button>
 <Stack direction={{xs:"column",sm:"row"}} sx={{mt:4,justifyContent:"space-between"}}><Typography variant="h6">Payment history</Typography>{selectedAssignment&&<Button variant="outlined" onClick={exportMember}>Download member CSV</Button>}</Stack><Stack spacing={1} sx={{mt:1}}>{memberPayments.map(p=><Paper key={p.id} variant="outlined" sx={{p:2}}><Stack direction={{xs:"column",sm:"row"}} sx={{justifyContent:"space-between",gap:1}}><Box><Typography sx={{fontWeight:700}}>{p.paymentDate} · {paymentMethodLabel(p.method)}</Typography><Typography>{formatEuro(p.amountCents)}{p.reversalOfPaymentId?" · Correction":""}</Typography>{p.note&&<Typography color="text.secondary">{p.note}</Typography>}</Box>{p.amountCents>0&&!payments.some(x=>x.reversalOfPaymentId===p.id)&&<Button onClick={()=>setCorrection(p)}>Correct entry</Button>}</Stack></Paper>)}</Stack></Paper>}
 {tab===1&&<Paper sx={{p:{xs:2,md:3}}}><Typography variant="h5" sx={{fontWeight:800,mb:2}}>Balances and reports</Typography><Stack direction={{xs:"column",sm:"row"}} spacing={2} sx={{mb:2}}><FormControl sx={{minWidth:200}}><InputLabel>Section</InputLabel><Select label="Section" value={section} onChange={e=>setSection(e.target.value)}><MenuItem value="all">All sections</MenuItem>{sections.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></FormControl><FormControl sx={{minWidth:180}}><InputLabel>Scout year</InputLabel><Select label="Scout year" value={period} onChange={e=>setPeriod(e.target.value)}>{policies.map(p=><MenuItem key={p.id} value={p.period}>{p.period}</MenuItem>)}</Select></FormControl>{canGroupReport&&<Button variant="outlined" onClick={exportBalances}>Download balance CSV</Button>}</Stack><Stack spacing={1}>{visibleAssignments.filter(a=>!period||a.period===period).map(a=>{const b=balanceFor(a,payments);return <Paper key={a.id} variant="outlined" sx={{p:2}} data-testid={`subs-balance-${a.memberId}`}><Typography sx={{fontWeight:800}}>{a.memberName} · {a.section}</Typography><Typography>{formatEuro(b.dueCents)} due · {formatEuro(b.paidCents)} paid · {b.remainingCents<0?`${formatEuro(-b.remainingCents)} credit`:`${formatEuro(b.remainingCents)} remaining`}</Typography><Stack direction="row" spacing={1} sx={{mt:1,flexWrap:"wrap"}}>{a.accountId?<><Chip size="small" label="Shared family account"/><Chip size="small" label={`${a.accountChildCount} members`}/></>:a.familyType&&a.familyPosition?<><Chip size="small" label={familyTypeLabel(a.familyType)}/><Chip size="small" label={`Member ${a.familyPosition}`}/></>:<Chip size="small" label={rateCategoryLabel(a.category)}/>}</Stack></Paper>;})}</Stack></Paper>}
 <Dialog open={confirmOpen} onClose={()=>!saving&&setConfirmOpen(false)}><DialogTitle>Confirm subs payment</DialogTitle><DialogContent dividers><Typography><strong>{selected?.displayName}</strong> · {selected?.section}</Typography><Typography>{formatEuro(amount?parseEuroToCents(amount):0)} by {paymentMethodLabel(method)} on {paymentDate}</Typography><Typography>Scout year: {period}</Typography>{selectedAssignment?.accountId&&<Typography>Applied to the shared family account.</Typography>}{selectedBalance&&<Typography>Resulting remaining balance: {formatEuro(selectedBalance.remainingCents-(amount?parseEuroToCents(amount):0))}</Typography>}</DialogContent><DialogActions><Button onClick={()=>setConfirmOpen(false)}>Cancel</Button><Button variant="contained" disabled={saving} onClick={()=>void submitPayment()}>{saving?"Recording…":"Confirm payment"}</Button></DialogActions></Dialog>
 <Dialog open={Boolean(correction)} onClose={()=>!saving&&setCorrection(null)}><DialogTitle>Correct payment entry</DialogTitle><DialogContent dividers><Alert severity="warning" sx={{mb:2}}>The original payment remains in history. An exact linked reversal will be added to the same {correction?.accountId?"family account":"member ledger"}.</Alert><TextField autoFocus required fullWidth label="Correction reason" value={correctionReason} onChange={e=>setCorrectionReason(e.target.value)}/></DialogContent><DialogActions><Button onClick={()=>setCorrection(null)}>Cancel</Button><Button color="warning" variant="contained" disabled={saving||!correctionReason.trim()} onClick={()=>void reverse()}>Record correction</Button></DialogActions></Dialog>
 </Container></Box>;
}
