import { readFile } from "node:fs/promises";
import { after,before,beforeEach,test } from "node:test";
import { assertFails,assertSucceeds,initializeTestEnvironment } from "@firebase/rules-unit-testing";
import { collection,deleteDoc,doc,getDoc,getDocs,query,serverTimestamp,setDoc,updateDoc,where } from "firebase/firestore";
let env; const projectId="coolock-ardlea-scouts";
const member=(section="Cubs")=>({displayName:"Member One",section,status:"active"});
const policy=(by="treasurer")=>({period:"2026/27",effectiveFrom:"2026-09-01",standardCents:10000,leaderChildCents:7000,siblingCents:8500,version:1,createdBy:by,createdAt:serverTimestamp()});
const payment=(by="leader-cubs",overrides={})=>({memberId:"m1",memberName:"Member One",section:"Cubs",period:"2026/27",amountCents:5000,method:"cash",paymentDate:"2026-09-09",reversalOfPaymentId:"",note:"",recordedBy:by,createdAt:serverTimestamp(),...overrides});
async function seed(entries){await env.withSecurityRulesDisabled(async c=>{for(const [path,data] of entries)await setDoc(doc(c.firestore(),path),data);});}
before(async()=>{env=await initializeTestEnvironment({projectId,firestore:{rules:await readFile("firestore.rules","utf8"),host:"127.0.0.1",port:8080}});}); beforeEach(async()=>env.clearFirestore()); after(async()=>env.cleanup());
test("section leader records and reads own section but is denied cross-section",async()=>{await seed([["adminUsers/leader-cubs",{active:true,role:"leader",sections:["Cubs"]}],["members/m1",member()],["members/m2",{...member("Scouts"),displayName:"Scout Two"}]]);const db=env.authenticatedContext("leader-cubs").firestore();await assertSucceeds(setDoc(doc(db,"subsPayments/p1"),payment()));await assertSucceeds(getDocs(query(collection(db,"subsPayments"),where("section","==","Cubs"))));await assertFails(setDoc(doc(db,"subsPayments/p2"),payment("leader-cubs",{memberId:"m2",memberName:"Scout Two",section:"Scouts"})));await assertFails(getDocs(query(collection(db,"subsPayments"),where("section","==","Scouts"))));});
test("Treasurer and Group Leader manage group-wide while ordinary leader cannot set rates",async()=>{await seed([["adminUsers/treasurer",{active:true,role:"leader",sections:["Group"]}],["organisationLeadership/treasurer",{active:true,scoutingRole:"Group Treasurer"}],["adminUsers/gl",{active:true,role:"leader",sections:["Group"]}],["organisationLeadership/gl",{active:true,scoutingRole:"Group Leader"}],["adminUsers/leader",{active:true,role:"leader",sections:["Cubs"]}],["members/m1",member()]]);const td=env.authenticatedContext("treasurer").firestore();const gd=env.authenticatedContext("gl").firestore();const ld=env.authenticatedContext("leader").firestore();await assertSucceeds(setDoc(doc(td,"subsRatePolicies/2026-v1"),policy()));await assertSucceeds(setDoc(doc(gd,"subsPayments/group-payment"),payment("gl")));await assertFails(setDoc(doc(ld,"subsRatePolicies/no"),policy("leader")));});
test("assignments snapshot a valid policy and authoritative member identity",async()=>{await seed([["adminUsers/treasurer",{active:true,role:"leader",sections:["Group"]}],["organisationLeadership/treasurer",{active:true,scoutingRole:"Group Treasurer"}],["members/m1",member()],["subsRatePolicies/2026-v1",{...policy(),createdAt:new Date()}]]);const db=env.authenticatedContext("treasurer").firestore();const base={memberId:"m1",memberName:"Member One",section:"Cubs",period:"2026/27",category:"sibling",amountDueCents:8500,policyId:"2026-v1",policyVersion:1,sibling:true,leaderChild:false,classifiedBy:"treasurer",createdAt:serverTimestamp()};await assertSucceeds(setDoc(doc(db,"subsAssignments/m1-2026"),base));await assertFails(setDoc(doc(db,"subsAssignments/bad-name"),{...base,memberName:"Other"}));await assertFails(setDoc(doc(db,"subsAssignments/bad-rate"),{...base,amountDueCents:8400}));});
test("payments reject malformed methods, identity changes and mutation",async()=>{await seed([["adminUsers/leader-cubs",{active:true,role:"leader",sections:["Cubs"]}],["members/m1",member()],["subsPayments/original",{...payment(),createdAt:new Date()}]]);const db=env.authenticatedContext("leader-cubs").firestore();await assertFails(setDoc(doc(db,"subsPayments/bad-method"),payment("leader-cubs",{method:"card"})));await assertFails(setDoc(doc(db,"subsPayments/bad-member"),payment("leader-cubs",{memberName:"Wrong"})));await assertFails(updateDoc(doc(db,"subsPayments/original"),{amountCents:1}));await assertFails(deleteDoc(doc(db,"subsPayments/original")));});
test("corrections are exact linked reversals and parents remain denied",async()=>{await seed([["adminUsers/leader-cubs",{active:true,role:"leader",sections:["Cubs"]}],["members/m1",member()],["subsPayments/original",{...payment(),createdAt:new Date()}],["parentAccounts/parent",{status:"approved",memberIds:["m1"],linkedSections:["Cubs"]}]]);const db=env.authenticatedContext("leader-cubs").firestore();const reversal=payment("leader-cubs",{amountCents:-5000,reversalOfPaymentId:"original",note:"Wrong member"});await assertFails(setDoc(doc(db,"subsPayments/arbitrary"),reversal));await assertFails(setDoc(doc(db,"subsPayments/reversal-original"),{...reversal,amountCents:-4999}));await assertSucceeds(setDoc(doc(db,"subsPayments/reversal-original"),reversal));const parent=env.authenticatedContext("parent").firestore();await assertFails(getDoc(doc(parent,"subsPayments/original")));await assertFails(setDoc(doc(parent,"subsPayments/no"),payment("parent")));});
