import assert from "node:assert/strict";
import test from "node:test";
import { balanceFor, createPaymentReversal, parseEuroToCents, rateForCategory, validatePayment, validatePolicy, type SubsAssignment, type SubsPayment, type SubsRatePolicy } from "../../src/services/subsLogic.ts";

const policy: SubsRatePolicy={id:"2026-v1",period:"2026/27",effectiveFrom:"2026-09-01",standardCents:10000,leaderChildCents:7000,siblingCents:8500,version:1};
const assignment: SubsAssignment={id:"m1--2026",memberId:"m1",memberName:"Member One",section:"Cubs",period:"2026/27",category:"standard",amountDueCents:10000,policyId:policy.id,policyVersion:1,sibling:false,leaderChild:false};
const payment=(amountCents:number,id="p1"):SubsPayment=>({id,memberId:"m1",memberName:"Member One",section:"Cubs",period:"2026/27",amountCents,method:"cash",paymentDate:"2026-09-09",reversalOfPaymentId:"",note:"",recordedBy:"leader"});

test("parses euro amounts into integer cents without floating point storage",()=>{ assert.equal(parseEuroToCents("5"),500); assert.equal(parseEuroToCents("5.2"),520); assert.equal(parseEuroToCents("5,25"),525); assert.throws(()=>parseEuroToCents("5.999")); assert.throws(()=>parseEuroToCents("-1")); });
test("selects explicit categories without guessing or stacking discounts",()=>{ assert.equal(rateForCategory(policy,"standard"),10000); assert.equal(rateForCategory(policy,"leader-child"),7000); assert.equal(rateForCategory(policy,"sibling"),8500); });
test("historical assignment remains snapshotted after policy changes",()=>{ const changed={...policy,standardCents:12000,version:2}; assert.equal(assignment.amountDueCents,10000); assert.equal(rateForCategory(changed,"standard"),12000); });
test("derives partial, paid and credit balances from ledger entries",()=>{ assert.deepEqual(balanceFor(assignment,[payment(4000)]),{dueCents:10000,paidCents:4000,remainingCents:6000}); assert.equal(balanceFor(assignment,[payment(10000)]).remainingCents,0); assert.equal(balanceFor(assignment,[payment(11000)]).remainingCents,-1000); });
test("exact reversals preserve auditable correction provenance",()=>{ const original=payment(4000); const reversal=createPaymentReversal(original,"Wrong member"); assert.equal(reversal.amountCents,-4000); assert.equal(reversal.reversalOfPaymentId,"p1"); assert.equal(balanceFor(assignment,[original,{...reversal,id:"reversal-p1",recordedBy:"treasurer"}]).paidCents,0); });
test("validates policies and positive controlled-method payments",()=>{ const {id:policyId,...policyInput}=policy; const {id:paymentId,recordedBy,createdAt,...paymentInput}=payment(500); void policyId; void paymentId; void recordedBy; void createdAt; assert.doesNotThrow(()=>validatePolicy(policyInput)); assert.throws(()=>validatePolicy({...policyInput,standardCents:-1})); assert.doesNotThrow(()=>validatePayment(paymentInput)); assert.throws(()=>validatePayment({...paymentInput,amountCents:0})); assert.throws(()=>validatePayment({...paymentInput,method:"card" as never})); });
